import { useEffect,useState } from 'react';
import { Link } from 'react-router-dom';
import { useAdmin } from './useAdmin';
export default function CircuitoComercial(){
 const {request}=useAdmin();const [view,setView]=useState('pendientes-entrega'),[rows,setRows]=useState([]),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[version,setVersion]=useState(0),[sort,setSort]=useState('fecha'),[pending,setPending]=useState(true),[action,setAction]=useState(null);
 useEffect(()=>{let active=true;setLoading(true);setError('');setAction(null);request(`/admin/${view}?orden=${sort}&solo_pendientes=${pending}`).then(r=>{if(active)setRows(r);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[view,sort,pending,version]);
 async function save(e){e.preventDefault();setBusy(true);setError('');setMessage('');const values=Object.fromEntries(new FormData(e.currentTarget));try{
 if(view==='configuracion-empresa')await request('/admin/configuracion-empresa',{method:'PUT',body:JSON.stringify(values)});
 else if(view==='solicitudes')await request(`/admin/solicitudes/${action.id}`,{method:'PATCH',body:JSON.stringify(values)});
 else await request(`/admin/pedidos/${action.id}/${action.type}`,{method:'POST',body:JSON.stringify(values)});
 setMessage('Operación registrada.');setVersion(v=>v+1);
 }catch(err){setError(err.message);}finally{setBusy(false);}}
 const label={ 'pendientes-entrega':'Pendientes de entrega',entregados:'Histórico de entregados','cuenta-corriente':'Cuenta corriente',solicitudes:'Solicitudes de clientes','configuracion-empresa':'Correo del sector de ventas'};
 return <section aria-label="Circuito comercial"><h2>Pedidos, entregas y cobros</h2><p><Link to="/ayuda">Manual de uso</Link></p><label>Consultar <select disabled={busy} value={view} onChange={e=>{setView(e.target.value);setMessage('');}}>{Object.entries(label).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><button disabled={busy} onClick={()=>setVersion(v=>v+1)}>Actualizar</button>
 {view==='cuenta-corriente'&&<><p>Comprobantes internos del proyecto, sin validez fiscal. Archivar un pedido no elimina su deuda.</p><label>Ordenar por<select value={sort} onChange={e=>setSort(e.target.value)}><option value="fecha">Fecha</option><option value="cliente">Cliente</option></select></label><label><input type="checkbox" checked={pending} onChange={e=>setPending(e.target.checked)}/> Solo importes a cobrar</label></>}
 {error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}{loading?<p role="status">Cargando…</p>:<>
 {view==='configuracion-empresa'?<form onSubmit={save} className="admin-form" key={version}><label>Correo de ventas<input name="correo_ventas" type="email" required defaultValue={rows[0]?.correo_ventas||''}/></label><button disabled={busy}>Guardar destinatario</button><p>Se usa para nuevos comprobantes. No cambia mensajes que ya tengan destinatario.</p></form>:<div className="admin-table"><table><thead><tr>{Object.keys(rows[0]||{}).map(k=><th key={k}>{k.replaceAll('_',' ')}</th>)}{['pendientes-entrega','solicitudes'].includes(view)&&<th>Acciones</th>}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||r.pedido_id||i}>{Object.values(r).map((v,j)=><td key={j}>{v&&typeof v==='object'?<details><summary>Artículos</summary><pre>{JSON.stringify(v,null,2)}</pre></details>:String(v??'—')}</td>)}{view==='pendientes-entrega'&&<td><button disabled={busy||r.estado!=='confirmado'||!['listo','completado'].includes(r.estado_gestion)} onClick={()=>setAction({id:r.id,type:'entregar'})}>Registrar entrega</button><button disabled={busy} onClick={()=>setAction({id:r.id,type:'anular'})}>Anular</button></td>}{view==='solicitudes'&&<td><button disabled={busy||r.estado!=='pendiente'} onClick={()=>setAction({id:r.id})}>Responder</button></td>}</tr>)}</tbody></table>{!rows.length&&<p>No hay registros.</p>}</div>}
 </>}
 {action&&<form className="admin-form" onSubmit={save}><h3>{view==='solicitudes'?'Responder solicitud':action.type==='entregar'?'Confirmar entrega':'Confirmar anulación'} #{action.id}</h3>{view==='solicitudes'?<><p>Responder no modifica el pedido ni ejecuta un reembolso. Indicá lo realizado o por qué se rechaza.</p><label>Resultado<select name="estado"><option value="resuelta">Resuelta</option><option value="rechazada">Rechazada</option></select></label><label>Respuesta<textarea name="respuesta" required maxLength={1000}/></label></>:<><p>{action.type==='entregar'?'El pedido pasará al histórico de entregados.':'Solo se anulan directamente pedidos que no iniciaron el pago. Para los demás se requiere revisar Mercado Pago.'}</p><label>Motivo / observaciones<textarea name="motivo" required maxLength={1000}/></label></>}<button disabled={busy}>Confirmar</button><button type="button" disabled={busy} onClick={()=>setAction(null)}>Cerrar</button></form>}
 </section>;
}
